In [11]:
import numpy as np
scalar = np.array(38)
vector = np.array([1,4,6,5])
matrix = np.array([
    [1,2,3],
    [1,4,6]
])
print(scalar,scalar.ndim)
print(vector,vector.ndim)
print(matrix,matrix.ndim)

38 0
[1 4 6 5] 1
[[1 2 3]
 [1 4 6]] 2


In [5]:
tensor = np.array([[[[1]]]])
print(tensor,tensor.ndim)

[[[[1]]]] 4


In [7]:
print(matrix[-2,-3])

1


In [8]:
matrix.shape

(2, 3)

In [9]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar[1:3,1:2])

[[5]
 [8]]


In [12]:
print(vector[1:4])

[4 6 5]


In [13]:
three = np.array(
    [
        [
            [1,2,3],
            [3,4,3]
        ],
        [
            [9,2,6],
            [5,4,3]
        ]
    ]
)
print(three)

[[[1 2 3]
  [3 4 3]]

 [[9 2 6]
  [5 4 3]]]


In [18]:
cur = three.reshape(2,1,-1)
print(cur)

[[[1 2 3 3 4 3]]

 [[9 2 6 5 4 3]]]


In [ ]:
###Filtaring

In [19]:
ind = [0,2]
print(vector[ind])

[1 6]


In [20]:
print(np.sum(vector))

16


In [22]:
    print(np.sum(matrix,1))

[ 6 11]


In [24]:
print(np.random.rand())
print(np.random.rand(2,6))

0.18087133434186697
[[0.18321402 0.99168027 0.42020689 0.03128669 0.84017805 0.64377023]
 [0.96100641 0.83347569 0.6119878  0.63146357 0.50554999 0.0034957 ]]


In [54]:
print(np.random.randint(100))
lala = np.random.randint(100,size=(3,4))

79


In [56]:
print(lala)
np.random.shuffle(lala)
print(lala)

[[91 81 36 25]
 [ 1 47 49 39]
 [96 81 33 56]]
[[91 81 36 25]
 [ 1 47 49 39]
 [96 81 33 56]]
