In [1]:
import numpy as np

In [3]:
ar = np.array([1,2,3])
ar

array([1, 2, 3])

In [4]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
same_gap = np.linspace(1,10,20)
same_gap

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [7]:
np.random.rand(10)

array([0.37860685, 0.38257607, 0.66348091, 0.70839328, 0.99266567,
       0.25151594, 0.90243134, 0.85732364, 0.99243115, 0.3661327 ])

In [8]:
np.random.randn(10)

array([-1.32520151, -0.43395092, -1.31579664,  0.4299302 , -2.24430767,
        0.74492068, -0.46088587,  1.23985827, -0.44667528, -1.59682259])

In [9]:
np.random.randint(10,20,10)

array([17, 16, 14, 15, 19, 17, 12, 17, 16, 18])

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [12]:
arr.dtype

dtype('int64')

In [13]:
arr.size

6

In [14]:
arr.min()

np.int64(1)

In [15]:
arr.sum()

np.int64(21)

In [16]:
arr[0].sum()

np.int64(6)

In [17]:
np.sum(arr,axis = 1)

array([ 6, 15])

In [18]:
np.sum(arr,axis = 0)

array([5, 7, 9])

In [19]:
arr.argmax()

np.int64(5)

In [21]:
ar = np.arange(1,31)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [24]:
ar = ar.reshape(5,6)
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [25]:
a = np.arange(11,21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
a[4:]

array([15, 16, 17, 18, 19, 20])

In [29]:
ar = np.arange(1,31).reshape(6,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [31]:
ar[0:3,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [32]:
ar + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [36]:
sl = a[:4];

In [37]:
b = a

In [38]:
sl *= 5

In [39]:
a

array([275, 300, 325, 350,  15,  16,  17,  18,  19,  20])

In [40]:
b *= 5

In [41]:
a

array([1375, 1500, 1625, 1750,   75,   80,   85,   90,   95,  100])