In [3]:
!pip install numpy

In [4]:
import numpy as np
print(np.__version__)

2.4.3


In [12]:
myList = [1,2,3,4,5,6]
my_np_array = np.array(myList)
print(my_np_array)

[1 2 3 4 5 6]


In [9]:
print(type(myList))

<class 'list'>


In [10]:
print(type(my_np_array))

<class 'numpy.ndarray'>


In [13]:
print(my_np_array.dtype)

int64


In [14]:
print(my_np_array.shape)

(6,)


In [15]:
print(my_np_array.ndim)

1


In [20]:
de = np.zeros(
    shape=(6,3),
    dtype='int32'
)
print(de)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
de = np.full(
    shape=(4,3),
    fill_value = 12
)
print(de)

[[12 12 12]
 [12 12 12]
 [12 12 12]
 [12 12 12]]


In [26]:
iden = np.eye(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
em = np.empty( shape = (5,))
print(em)

[0.00000000e+000 8.34793070e-312 8.34793069e-312 8.34793069e-312
 2.35545354e-312]


In [28]:
em = em.astype('int')
print(em)

[0 0 0 0 0]


In [30]:
my_ar = np.arange(start = 1,stop = 11,step = 1)
print(my_ar)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
lin = np.linspace(
    start = 1,
    stop = 10,
    num = 13
)
print(lin)

[ 1.    1.75  2.5   3.25  4.    4.75  5.5   6.25  7.    7.75  8.5   9.25
 10.  ]
